development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql #redis
  url: postgres://oeuwllgwvfkwzs:52b136ad9c776af336fd86da33034c95186995eee6cd8d4700d3c47f4bce5de6@ec2-54-83-33-213.compute-1.amazonaws.com:5432/d1ssmnfk0iflk7 #<%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: sample_app_production
